### PR TITLE
fixing default basepath to contain primaryKey

### PR DESCRIPTION
**Pull request by pedrofs**
Hi,

simply adding the `{primaryKey}` to be in the path by default.

### CODE REVIEW

**Comment by pedrofs** [comment]
Just realized this `{primaryKey} substitution not allowed for new entities`

**Comment by josegonzalez** [comment]
Yeah, I'm not merging this for exactly that reason. You can always configure your basepath to be this anyhow.

**Comment by pedrofs** [comment]
Hey @josegonzalez but how to have a add form to upload images like that? Haven't you ever gone through such need? What do you suggest?

Thanks!

**Comment by josegonzalez** [comment]
Just use `{random}`. Your users don't care about the paths on disk, why should you?

**Comment by pedrofs** [comment]
Awesome, I haven't notice this `{random}`. Lack of attention, sorry for that.

Thanks!

**Pull request closed without merging**
