### PR TITLE
about the #191

### PR DESCRIPTION
**Pull request by maxmasetti**
here is a possible fix for the problem that happens when you try a reinsert twice the same file.

### CODE REVIEW

**Comment by davidyell** [comment]
Relates to #191 and #143

**Comment by davidyell** [comment]
Thanks for the PR, can you fix your indentation for PHPCS please. Then I can test this.

**Comment by maxmasetti** [comment]
hi, can't find the problem. It seems indentation is ok. May you give some help in finding the phpcs problem?

**Comment by davidyell** [comment]
Hey @maxmasetti did you check the build on Travis?

https://travis-ci.org/josegonzalez/cakephp-upload/jobs/31120228#L71

**Comment by maxmasetti** [comment]
hi, 
yes I did:
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
but reading code line by line no space used for indenting found at all.

max

**Pull request closed without merging**
